swagger: "2.0"

info:
  version: 1.0.0
  title: LinSTT
  description: A simple way to test LinSTT API, and to learn how to use API

schemes:
  - http
host: 127.0.0.1:8888
basePath: /

paths:
  /transcribe:
    post:
      tags:
        - "Speech-To-Text API"
      summary: Perform Speech-to-Text
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      - "text/plain"
      parameters: 
      - name: "file"
        in: "formData"
        description: "Audio File - Waveform Audio File Format is required. Best configuration (16KHz, 16b, mono)"
        required: true
        type: "file"
      responses:
        200:
          description: Successfully transcribe the audio
        400:
          description: Request error
        500:
          description: Server error
  /transcription/{PID}:
    get:
      tags:
        - "Speech-To-Text API"
      summary: Perform Speech-to-Text
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      - "text/plain"
      parameters: 
      - name: "PID"
        in: "path"
        description: "PID of a transcribe request"
        required: true
        type: "string"
      responses:
        200:
          description: Get transcription
        400:
          description: Invalid PID
  /get/pids:
    get:
      tags:
        - "Speech-To-Text API"
      summary: Get PIDs
      produces:
      - "application/json"
      responses:
        200:
          description: Get list of PIDs