swagger: "2.0"

info:
<<<<<<< HEAD
  version: 1.0.0
  title: LinSTT
  description: A simple way to test LinSTT API, and to learn how to use API

schemes:
  - http
host: localhost:8888
=======
  version: "1.0.0"
  title: LinTo-Platform-STT
  description: Speech To Text API
  contact:
    email: "support@linto.ai"
  license:
    name: "AGPLv3"
    url: "https://www.gnu.org/licenses/agpl-3.0.en.html"

schemes:
  - http
>>>>>>> next
basePath: /

paths:
  /transcribe:
    post:
      tags:
        - "Speech-To-Text API"
      summary: Perform Speech-to-Text
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      - "text/plain"
      parameters: 
      - name: "file"
        in: "formData"
<<<<<<< HEAD
        description: "Audio File - Waveform Audio File Format is required. Best configuration (16KHz, 16b, mono)"
=======
        description: "Audio File - WaveFile PCM 16b 16KHz"
>>>>>>> next
        required: true
        type: "file"
      responses:
        200:
          description: Successfully transcribe the audio
        400:
          description: Request error
        500:
          description: Server error
<<<<<<< HEAD
  /transcription/{jobid}:
    get:
      tags:
        - "Speech-To-Text API"
      summary: Perform Speech-to-Text
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      - "text/plain"
      parameters: 
      - name: "jobid"
        in: "path"
        description: "jobid of a transcribe request"
        required: true
        type: "string"
      responses:
        200:
          description: Get transcription
        400:
          description: Invalid jobid
  /jobids:
    get:
      tags:
        - "Speech-To-Text API"
      summary: Get jobids
      produces:
      - "application/json"
      responses:
        200:
          description: Get list of jobids
=======

  /healthcheck:
    get:
      tags:
        - "Health"
      summary: Check server health
      consumes:
      - "application/json"
      responses:
        200:
          description: Healthcheck passes
        400:
          description: Healthcheck fails
        500:
          description: Healthcheck fails
>>>>>>> next
