swagger: "2.0"

info:
  version: 1.0.0
  title: LinSTT
  description: A simple way to test LinSTT API, and to learn how to use API

schemes:
  - http
host: localhost:8888
basePath: /

paths:
  /transcribe:
    post:
      tags:
        - "Speech-To-Text API"
      summary: Perform Speech-to-Text
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      - "text/plain"
      parameters: 
      - name: "file"
        in: "formData"
        description: "Audio File (wav, mp3, aiff, flac, ogg)"
        required: true
        type: "file"
      - name: "nbrSpeaker"
        in: "formData"
        description: "Number of speakers in the audio"
        required: false
        type: "number"
        default: 1
      - name: "speaker"
        in: "formData"
        description: "Do speaker diarization"
        required: false
        type: "string"
        enum: [ "Yes", "No" ]
        default: "No"
      responses:
        200:
          description: Successfully transcribe the audio
